apiVersion: v1
kind: ConfigMap
metadata:
  name: ciis-config
data:
  FRONTEND_ORIGIN: {{ .Values.config.frontendOrigin | quote }}

  STORAGE_ENDPOINT_URL: {{ .Values.config.storageEndpointUrl | quote }}
  STORAGE_BUCKET: {{ .Values.config.storageBucket | quote }}
  STORAGE_REGION: {{ .Values.config.storageRegion | quote }}
  STORAGE_USE_SSL: "false"
  STORAGE_ACCESS_KEY: "test"
  STORAGE_SECRET_KEY: "test"

  SQS_ENDPOINT_URL: {{ .Values.config.sqsEndpointUrl | quote }}
  SQS_REGION: {{ .Values.config.sqsRegion | quote }}
  SQS_ACCESS_KEY: "test"
  SQS_SECRET_KEY: "test"
  SQS_ANALYSIS_QUEUE_NAME: {{ .Values.config.sqsQueueName | quote }}
  SQS_ANALYSIS_DLQ_NAME: {{ .Values.config.sqsDlqName | quote }}

  WORKER_POLL_SECONDS: {{ .Values.config.workerPollSeconds | quote }}
  METRICS_COLLECTION_SECONDS: {{ .Values.config.metricsCollectionSeconds | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelEndpoint | quote }}
