apiVersion: v1
kind: Service
metadata:
  name: floci-local
spec:
  ports:
    - name: aws
      port: 4566
      targetPort: 4566
---
apiVersion: v1
kind: Endpoints
metadata:
  name: floci-local
subsets:
  - addresses:
      - ip: {{ .Values.config.flociIp | quote }}
    ports:
      - name: aws
        port: 4566
        protocol: TCP
