services:
  localstack:
    image: localstack/localstack:3
    container_name: ciis-localstack

    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 0

    ports:
      - "${CI_LOCALSTACK_PORT:-54566}:4566"

    volumes:
      - ciis_localstack_data:/var/lib/localstack
      - ./infra/localstack/init-sqs.sh:/etc/localstack/init/ready.d/init-sqs.sh

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:4566/_localstack/health"
        ]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  ciis_localstack_data:
